version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "${SERVER_PORT:-8080}:80"
      - "${SUB_SERVER_PORT:-8081}:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - php
      - mysql
    networks:
      - web

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    restart: always
    ports:
      - "${APP_PORT:-9000}:9000"
      - "${SUB_APP_PORT:-9001}:9000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - web

  mysql:
    image: mysql:8.0.30
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/var/log/mysql
    networks:
      - web

networks:
  web:
    driver: bridge
